---
dingrogu:
  url: http://localhost:8080
rexclient:
  url: http://rex-newcastle-devel.apps.ocp-c1.prod.psi.redhat.com
quarkus:
  oidc:
    enabled: false
  oidc-client:
    enabled: false
    auth-server-url: http://localhost:8180/auth/realms/quarkus
    client-id: dustin
    credentials:
      secret: 1234